name: David's Notebook
description: Keeping notes on data science
meta_description: "David's Notebook, Keeping notes on data science."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: '/'
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'David Cairuz'
