# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Home', folder: '.', file: ''}
- {name: 'Dashboard de contaminados', folder: 'pages', file: 'dashboard_contaminados.html'}
- {name: 'Dashboard de mortes', folder: 'pages', file: 'dashboard_mortes.html'}
- {name: 'Mapas', folder: 'pages', file: 'maps.html'}
- {name: 'Gráficos', folder: 'pages', file: 'graphs.html'}
- {name: 'Tabela', folder: 'pages', file: 'tables.html'}
- {name: 'Sobre', folder: 'pages', file: 'about.html'}
- {name: 'Contato', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:davidcairuz@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Próximo'
  previous_page: 'Anterior'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'
